# -*- coding: utf-8 -*-
"""3weekhomework1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GFLqO1le_pxjXIQWo6oUEd3MiJSUYo2G
"""

C = int(input())
F = C*9/5+32

print(f'섭씨{C}도는 화씨{F}도이다.')

