# -*- coding: utf-8 -*-
"""3weekhomewprk2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UVCOn2keUfxBqB8kz9PbMG8F1evzSDwg
"""

r = int(input())

S = 3.14*r**2
l = 2*3.14*r
print(f'넓이는{S}이고, 원주는{l}이다.')