# -*- coding: utf-8 -*-
"""3weekhomework3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QvkqAbc8NdTBrmrSMymQ4W7y9UWDE7x2
"""

a = int(input())
b = int(input())
c = int(input())

Plus = a+b+c
Average = Plus/3
print(f'합은 {Plus}이고, 평균은{Average}입니다.')