# -*- coding: utf-8 -*-
"""3weekhomework4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y-ddLldCji5eJpaQolsopgsPMdearj60
"""

a = int(input())
b = int(input())

h = int(b/100)
t = int((b%100)/10)
o = int(b%10)

hh = int(a*h)
tt = int(a*t)
oo = int(a*o)
print(oo, tt, hh, a*b)