# -*- coding: utf-8 -*-
"""4weekhw2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16A3_DjBZUOze01RYCysL7wDzAG_V9ybo
"""

n = 542

for i in range(n+1):
  r = True
  if i < 2 :
    r = False
  for j in range(2, i) :
    if i%j == 0 :
      r = False
  if r is True :
    print(i, end = " ")