# -*- coding: utf-8 -*-
"""4weekhw4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rASXhEyxSLVInQco7fU3RqFY4Ylo3_xi
"""

n = int(input()) #만약 5가 입력되면
pac = 1
if 0 < n < 15 :
  for i in range(n): #i가 0부터 n-1까지 도달하는동안
    pac = pac*(i+1) #pac= 1*(0+1), pac = 1*(1+1), pac = 2*(2+1), pac = 6*(3+1), pac = 24*(4+1)
  pac_list = list(map(int,str(pac))) #pac값을 리스트로 문자열로 변환해서 리스트로 만듦
                                     #출력하면 [1, 2, 0]으로 출력.....
  if pac_list[-1] == 0 :
      print(pac_list[-2]) #맨 끝자리가 0이면 그 앞에거 출력
  else :
      print(pac_list[-1]) #0 아니면 그냥 맨 끝자리 출력
else :
  print("입력범위 초과.")