# -*- coding: utf-8 -*-
"""4weekhw5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kfPn1YtTk7rqezdT7EdaQfRuIGRLuLN5
"""

n = int(input())
pac = 1
for i in range(2, n+1): 
  pac = pac*i
  while True:
    if str(pac)[-1] == "0":
      pac = pac//10
    else :
      break
print(str(pac)[-5:])