# -*- coding: utf-8 -*-
"""3weekhomework5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1he_1NpmvQSw1ZSysoI_fAIfE6jVr93Wu
"""

bul = int(input())
seo = int(bul - 543)
if 1000<bul<3000 :
    print(seo)
else :
    print('입력값이 범위를 넘어섰습니다.')