# -*- coding: utf-8 -*-
"""3weekhomework6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HPentOBRmGwcpuehHPCwD6HByy5Z6tbP
"""

a,b = input().split("-")
print(a+b)