# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y1gDwa6V8d_Qv7ljvUr3BCJJt7f0yyL1
"""

C = int(input())
F = C*9/5+32

print(f'섭씨{C}도는 화씨{F}도이다.')